// What's New entries shown in Settings → About → App Version.
// Newest first. Bump app.json's "version" and add a new entry here on release.
export const CHANGELOG = [
  {
    version: '1.5.0',
    date: 'August 5, 2026',
    highlights: [
      'Import your whole library from AniList or MyAnimeList in one tap — Settings → Trackers. It only ever adds or moves you forward, so it can never undo progress you already have',
      'The bottom tab bar no longer sits on top of your content — the last row of Library, the badges on your Profile, and the poll in Community were all being clipped by it',
      'The Home feed no longer breaks when you rotate your device, unfold a foldable, or use split-screen — cards used to stop snapping to the screen properly',
      'Comments, Direct Messages and Notifications now load older entries as you scroll instead of silently stopping at the first batch',
      'The whole app is now genuinely translated in all six languages — pop-ups, alerts and error screens were still showing English even when you had another language selected',
      'Reading ambience now keeps playing when your screen locks mid-chapter instead of cutting out',
      'A banner now tells you when you have lost connection, rather than screens quietly failing to load',
      'Much better screen-reader support, and small icons like bookmark, share and spoiler are now far easier to tap accurately',
      'Sign-in, sign-up and the Creator dashboard no longer run under the notch or the home indicator on some phones',
      'Manga details, sign-in and a few other screens now use the space properly on tablets instead of stretching text edge to edge',
    ],
  },
  {
    version: '1.4.0',
    date: 'July 30, 2026',
    highlights: [
      'MangaRecap has been rebuilt from the ground up into a real cinematic story — ten redesigned slides with living cover-art backgrounds, and a whole visual style generated from what YOU actually read (manga, manhwa, and manhua readers each get a structurally different look, not just a different color)',
      'MangaRecap now shows how this half compares to your last one, where you rank among your friends, "you and @friend both read this" callouts, your single loudest comment, and a shareable reading DNA code',
      'Share your MangaRecap as a real image now instead of plain text — choose a Stories-shaped or square crop — and compare your half side-by-side against a friend',
      'Library badges (new-chapter counts, site icons) now show up instantly from last session instead of popping in a few seconds after the screen opens',
      'Fixed a rare bug where a bad measurement on a tapped cover could paint a large ghost box over the whole app',
      'Fixed message replies getting hidden behind the keyboard on some devices in Direct Messages',
      'Fixed a tap on a Feed cover silently doing nothing on some devices',
      'Fixed the "Adult" mood filter on For You always coming up empty and quietly falling back to general picks',
      'Fixed manga detail pages occasionally reopening as a blank grey screen',
      'Added screen-reader labels across sign-in, sign-up, and password fields',
    ],
  },
  {
    version: '1.3.1',
    date: 'July 28, 2026',
    highlights: [
      'Like, save, and share counts in the Feed now stick instead of snapping back to the old number when you keep scrolling',
      'Tapping a notification opens what it points at even when the app was fully closed — it used to just dump you on the home screen',
      'Turning notifications back on after switching them all off actually starts delivering again, instead of staying silent until the next app restart',
      '"New Chapter" badges in your Library no longer vanish on their own, and now show up on Bookmarked and Completed too',
      'Picking a specific site under "Read Available" now really opens that site, instead of quietly falling back to the last one you used',
    ],
  },
  {
    version: '1.3.0',
    date: 'July 19, 2026',
    highlights: [
      'Manga detail pages got a full redesign — genres, a "You Might Also Like" shelf, character art, and real site logos under Read Available',
      'Reader: resume picks up on the exact page (not just the chapter), plus a night-reading warm filter, double-page spread on tablets/landscape, and bigger batch downloads (5/10/25/whole series)',
      'Library: tap the filter icon to browse by genre, and fixed several bugs — duplicate entries, wrong covers showing under the wrong title, and junk like "Recent Searches" appearing as if it were a manga you were reading',
      'Signing out now fully clears your data — no more mixing up favorites or settings between accounts on the same device',
      'Guest accounts can upgrade to a real account anytime from Settings without losing any progress',
      'Comments can go two replies deep instead of flattening everything onto the top-level comment',
      'Friend search now matches as you type instead of needing the exact username',
      'Tapping a cover in the Feed opens its detail page (it used to jump straight into the reader)',
      'Alerts and confirmations now match the app\'s look instead of a plain system popup',
      'Fixed the splash screen and the app\'s intro animation on update',
    ],
  },
  {
    version: '1.2.4',
    date: 'July 19, 2026',
    highlights: [
      'Haptic feedback on likes, bookmarks, shares, and comments',
      'Smoother feed swiping, with a cover animation into each series page',
      'Message reactions, swipe-to-reply, and typing indicators in DMs',
      'Skip sign-in and start reading right away — create an account anytime later from Settings',
    ],
  },
  {
    version: '1.2.0',
    date: 'July 10, 2026',
    highlights: [
      'Tap a recommendation\'s description for a full detail page — synopsis, genres, status, and content warnings',
      'A clean "Reader Mode" for sites other than MangaDex — same distraction-free view MangaDex chapters already get',
      'Notification settings now cover comments and DMs, and DMs actually send a push now',
      'Fixed library saves (bookmarks, progress) silently failing on flaky connections — now retries once',
      'Adult content only blurs true 18+ material, not everyday covers',
    ],
  },
  {
    version: '1.1.0',
    date: 'July 9, 2026',
    highlights: [
      'The app now updates itself — no more reinstalling APKs for most changes',
      'Sign in with your username or email, password underneath',
      'Editable display name, separate from your permanent @handle',
      'Fixed Google sign-in',
      'Redesigned, shorter onboarding',
      'Fixed a crash when swiping recommendation cards, and a username field typing bug',
    ],
  },
  {
    version: '1.0.0',
    date: 'July 9, 2026',
    highlights: [
      'Vertical (webtoon) and paged (manga) reading modes, with ambience sound, force-dark mode, and a screen dimmer',
      'Download chapters for offline reading',
      'Friends, direct messages, and per-series discussion threads with spoiler tagging',
      'Badges, medal tiers, and the Weapon Vault collection',
      'Live leaderboard and personalized "For You" recommendations',
      'Refreshed app icon and brand color, plus reader stability fixes',
    ],
  },
];
