// Builds the intro montage frames from the curated famous-panel sources in
// assets/intro-src/ (downloaded from fandom/KYM CDNs and visually verified).
// Converts each to stark B&W ink (Marvel-intro style), crops a square window
// around the panel's focal point, writes assets/intro/panel-XX.jpg + panels.js.
// To add a frame: drop the image into assets/intro-src/, add a SOURCES entry, rerun:
//   node scripts/fetchIntroPanels.js
const { createCanvas, loadImage } = require('canvas');
const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

const TILE = 384;
const JPEG_QUALITY = 0.85;

// Riffle order. fx/fy = crop-window center as a fraction of image size.
const SOURCES = [
  { file: 'gojo_nah.jpg',       fx: 0.42, fy: 0.50 }, // JJK — Gojo "Nah, I'd win"
  { file: 'guts_struggler.png', fx: 0.50, fy: 0.28 }, // Berserk — Eclipse
  { file: 'luffy_peak.png',     fx: 0.55, fy: 0.50 }, // One Piece — Gear 5 line art
  { file: 'jinwoo.jpg',         fx: 0.50, fy: 0.30 }, // Solo Leveling — rain
  { file: 'saitama_punch.png',  fx: 0.45, fy: 0.50 }, // OPM — Serious Punch spread
  { file: 'baam_536.png',       fx: 0.50, fy: 0.22 }, // Tower of God — Baam
  { file: 'denji_pochita.png',  fx: 0.50, fy: 0.35 }, // Chainsaw Man — full page
  { file: 'thorfinn_1002.png',  fx: 0.50, fy: 0.50 }, // Vinland Saga — young Thorfinn
  { file: 'eren_ocean.png',     fx: 0.50, fy: 0.45 }, // AOT — the ocean
  { file: 'eren_declares.png',  fx: 0.50, fy: 0.50 }, // AOT — declaration spread (climax)
];

const srcDir = path.join(__dirname, '..', 'assets', 'intro-src');
const outDir = path.join(__dirname, '..', 'assets', 'intro');

async function processPanel(filePath, fx, fy) {
  // Decode through sharp first — fandom's CDN serves WebP regardless of extension,
  // and node-canvas can't read WebP.
  const decoded = await sharp(filePath).png().toBuffer();
  const img = await loadImage(decoded);
  const side = Math.min(img.width, img.height);
  const sx = Math.min(Math.max(img.width * fx - side / 2, 0), img.width - side);
  const sy = Math.min(Math.max(img.height * fy - side / 2, 0), img.height - side);

  const canvas = createCanvas(TILE, TILE);
  const ctx = canvas.getContext('2d');
  ctx.imageSmoothingEnabled = true;
  ctx.imageSmoothingQuality = 'high';
  ctx.drawImage(img, sx, sy, side, side, 0, 0, TILE, TILE);

  // Stark B&W ink conversion: luminance -> levels -> S-curve
  const data = ctx.getImageData(0, 0, TILE, TILE);
  const px = data.data;
  for (let i = 0; i < px.length; i += 4) {
    const lum = 0.299 * px[i] + 0.587 * px[i + 1] + 0.114 * px[i + 2];
    let n = (lum - 30) / (225 - 30);
    n = Math.min(1, Math.max(0, n));
    n = n * n * (3 - 2 * n); // smoothstep S-curve for inky contrast
    const v = Math.round(n * 255);
    px[i] = px[i + 1] = px[i + 2] = v;
  }
  ctx.putImageData(data, 0, 0);

  return canvas.toBuffer('image/jpeg', { quality: JPEG_QUALITY });
}

(async () => {
  fs.mkdirSync(outDir, { recursive: true });
  for (const f of fs.readdirSync(outDir)) {
    if (/^panel-\d+\.jpg$/.test(f)) fs.unlinkSync(path.join(outDir, f));
  }

  const done = [];
  for (const { file, fx, fy } of SOURCES) {
    const filePath = path.join(srcDir, file);
    if (!fs.existsSync(filePath)) { console.warn(`SKIP ${file}: not found in assets/intro-src`); continue; }
    const tile = await processPanel(filePath, fx, fy);
    const name = `panel-${String(done.length + 1).padStart(2, '0')}.jpg`;
    fs.writeFileSync(path.join(outDir, name), tile);
    done.push(name);
    console.log(`${name}  <- ${file}  (${(tile.length / 1024).toFixed(0)}KB)`);
  }

  const manifest =
    '// Auto-generated by scripts/fetchIntroPanels.js — do not edit manually.\n' +
    'export default [\n' +
    done.map((n) => `  require('./${n}'),`).join('\n') +
    '\n];\n';
  fs.writeFileSync(path.join(outDir, 'panels.js'), manifest);
  console.log(`\n${done.length} frames. Manifest: assets/intro/panels.js`);
})();
